#配置Servlet容器
server:
    # 配置程序端口，默认为8080
    port: 1234
    # 配置默认访问路径，默认为/
    servlet:
      context-path: /dev-api
    # 配置Tomcat
    tomcat:
      # 配置Tomcat编码,默认为UTF-8
      uri-encoding: utf-8
      # 配置最大线程数
      max-threads: 1000
system:
  #注册用户默认密码
  defaultPwd: 123456
  #注册用户默认角色ID
  defaultRoleId: 100
  #注册用户默认组织机构ID
  defaultOrgId: 0
  #不需要数据权限过滤的角色key
  noDataFilterRole: DATA_NO_FILTER
  #用户每日收取短信上限
  smsTimes: 25
  #不同终端用户的超时时间（web用户3小时，app，微信，小程序时间自己定半年或永久）Long型，后面记得加l
  expireTime: "{web: 10800000l, app: 15768000000l}"
controller:
  #扫描controller中不需要鉴权的method
  scanPackage:
    classpath*:com/antplatform/*/*/action/*/*.class